In [1]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from IPython.display import display
from matplotlib import ticker
from pathlib import Path

In [3]:
# Пути к обработанным данным
# Путь к X части выборки с массивами в каждой ячейке
path_to_array_like_X_data = 'data\\Prepared data\\Run2\\X_data_array_like.xlsx' 
# Путь к X части выборки, с данными представленными с помощью иерархиеских индексов
path_to_hierarhical_X_data = 'data\\Prepared data\\Run2\\X_data_hierarhical.xlsx' 
# Путь к Y части выборки
path_to_Y_data = 'data\\Prepared data\\Run2\\Y_data(binary_classification).xlsx'

In [4]:
# прочесть файл X_data_array-like.xlsx
def get_array_like_X_df(path: str):
    df = pd.read_excel(path,index_col=[0])
    return df

In [5]:
# прочесть файл X_data_hierarhical.xlsx 
def get_hierarhical_X_df(path: str):
    df = pd.read_excel(path,index_col=[0,1])
    return df

In [6]:
# прочесть файл Y_data(binary_classification).xlsx
def get_Y_df(path: str):
    df = pd.read_excel(path,index_col=[0])
    return df

In [7]:
# чтение данных
arr_X_df = get_array_like_X_df(path_to_array_like_X_data)
display(arr_X_df)

,detector_0,detector_1,detector_2,detector_3,detector_4,detector_5,detector_6,detector_7,detector_8,detector_9,...,detector_390,detector_391,detector_392,detector_393,detector_394,detector_395,detector_396,detector_397,detector_398,detector_399
row,,,,,,,,,,,,,,,,,,,,,
0,[ 25.5 25.7 25.8 25.9 26.1 26.2...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.1 25.3 25.5 25.6 25.9 26. ...,[ 25.1 25.3 25.4 25.5 25.7 25.8...,[ 25.5 25.7 25.9 26. 26.1 26.3...,[ 25.5 25.7 25.9 26. 26.1 26.3...,[ 25.1 25.3 25.4 25.5 25.6 25.7...,[ 25.8 25.9 26. 26.1 26.2 26.4...,[ 25.8 25.9 26.1 26.2 26.3 26.5...,[ 25.8 26. 26.1 26.3 26.4 26.5...,...,[ 24.8 25.1 25.2 25.3 25.5 25.6...,[ 25. 25.3 25.4 25.5 25.7 25.7...,[ 24.8 24.9 25.1 25.2 25.3 25.5...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 20. 24.9 25.1 25.2 25.3 25.4...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 25. 25.2 25.3 25.4 25.6 25.7...,[ 25. 25.2 25.3 25.5 25.6 25.7...
1,[ 25.5 25.7 25.8 25.9 26.1 26.2...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.1 25.3 25.5 25.6 25.7 25.9...,[ 25.3 25.4 25.6 25.7 25.7 25.8...,[ 25.5 25.7 25.9 26. 26.1 26.3...,[ 25.5 25.7 25.9 26. 26.1 26.3...,[ 25.1 25.2 25.3 25.5 25.6 25.7...,[ 25.8 26.1 26.2 26.3 26.4 26.6...,[ 25.8 26. 26.1 26.2 26.3 26.5...,[ 25.8 26. 26.1 26.3 26.4 26.6...,...,[ 24.8 25. 25.2 25.3 25.5 25.6...,[ 25. 25.1 25.3 25.4 25.5 25.7...,[ 24.8 25. 25.1 25.3 25.4 25.5...,[ 19.7 24.7 25. 25.1 25.2 25.4...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 20. 24.9 25.1 25.2 25.3 25.5...,[ 24.7 24.9 25. 25.1 25.3 25.4...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 24.8 25. 25.1 25.3 25.4 25.5...,[ 25. 25.2 25.3 25.5 25.6 25.7...
2,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.1 25.4 25.5 25.6 25.7 25.9...,[ 25.1 25.4 25.5 25.6 25.7 25.9...,[ 25.6 25.8 25.9 26. 26.1 26.3...,[ 25.3 25.6 25.7 25.8 25.9 26.1...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.1 25.3 25.3 25.5 25.6 25.7...,[ 25.9 26.2 26.3 26.4 26.6 26.7...,[ 25.6 25.9 26. 26.1 26.3 26.5...,[ 25.6 25.9 26. 26.1 26.3 26.5...,...,[ 24.8 25.1 25.2 25.3 25.4 25.7...,[ 25.1 25.3 25.5 25.6 25.7 25.8...,[ 24.8 25. 25.1 25.3 25.4 25.7...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 24.7 24.9 25. 25.1 25.3 25.4...,[ 19.9 20. 24.8 25. 25.1 25.3...,[ 24.7 24.8 24.9 25. 25.1 25.3...,[ 24.7 24.9 25. 25.1 25.3 25.4...,[ 24.8 25.1 25.2 25.3 25.5 25.5...,[ 25. 25.2 25.3 25.5 25.6 25.7...
3,[ 25.3 25.5 25.6 25.7 25.9 26. ...,[ 25.1 25.4 25.5 25.6 25.7 25.9...,[ 25.1 25.4 25.5 25.6 25.8 25.9...,[ 25.8 25.9 26. 26.2 26.3 26.5...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.1 25.4 25.5 25.7 25.8 25.9...,[ 25.9 26.2 26.3 26.5 26.6 26.7...,[ 25.6 25.9 26. 26.1 26.3 26.4...,[ 25.6 25.9 26.1 26.2 26.3 26.5...,...,[ 24.8 25.1 25.2 25.3 25.4 25.6...,[ 25.1 25.3 25.5 25.6 25.7 25.8...,[ 24.8 25. 25.1 25.3 25.4 25.6...,[ 24.8 25.1 25.2 25.3 25.5 25.6...,[ 24.8 25.1 25.2 25.3 25.5 25.6...,[ 20. 24.8 25. 25.1 25.3 25.4...,[ 20. 24.6 24.9 25. 25.1 25.3...,[ 19.5 24.7 24.9 25. 25.1 25.3...,[ 24.8 25.1 25.2 25.3 25.4 25.5...,[ 25. 25.2 25.3 25.4 25.6 25.7...
4,[ 25.1 25.4 25.5 25.6 25.7 25.9...,[ 25.1 25.4 25.5 25.6 25.7 25.9...,[ 25.1 25.3 25.5 25.6 25.7 25.9...,[ 25.8 25.9 26.1 26.3 26.4 26.5...,[ 25.3 25.6 25.7 25.8 25.9 26.1...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.3 25.5 25.6 25.7 25.9 26. ...,[ 25.9 26.2 26.3 26.4 26.6 26.7...,[ 25.5 25.5 25.7 25.9 26. 26.2...,[ 25.6 25.9 26.1 26.2 26.3 26.5...,...,[ 24.8 25. 25.2 25.3 25.5 25.6...,[ 25.1 25.2 25.3 25.4 25.5 25.7...,[ 24.8 25. 25.1 25.3 25.4 25.6...,[ 24.8 25.1 25.2 25.3 25.5 25.7...,[ 24.8 25.1 25.2 25.3 25.5 25.6...,[ 24.8 25. 25.1 25.3 25.4 25.6...,[ 24.7 24.9 25. 25.1 25.3 25.5...,[ 19.5 24.7 24.9 25. 25.1 25.3...,[ 24.8 25. 25.1 25.3 25.4 25.5...,[ 25. 25.2 25.3 25.5 25.6 25.7...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,[ 24.8 24.9 25.1 25.3 25.4 25.5...,[ 25.5 25.7 25.8 25.9 26.1 26.2...,[ 25.6 25.9 26. 26.1 26.3 26.4...,[ 25.6 25.8 25.9 26.1 26.2 26.3...,[ 25.3 25.5 25.7 25.8 25.9 26. ...,[ 25.6 25.9 26. 26.1 26.2 26.4...,[ 25.8 25.9 26.1 26.2 26.3 26.5...,[ 25.9 26.3 26.4 26.5 26.7 26.8...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.6 25.9 26. 26.1 26.3 26.4...,...,[ 26.3 26.5 26.7 26.8 26.9 27.1...,[ 26.1 26.2 26.4 26.5 26.7 26.8...,[ 26.9 27.2 27.3 27.4 27.5 27.7...,[ 26.7 27. 27.1 27.2 27.4 27.5...,[ 26.4 26.7 26.8 26.9 27.1 27.2...,[ 25.9 26.2 26.3 26.5 26.6 26.7...,[ 26.7 27. 27.1 27.2 27.4 27.5...,[ 26.4 26.7 26.8 26.9 27.1 27.2...,[ 26.1 26.3 26.5 26.6 26.7 26.9...,[ 25.5 25.6 25.7 25.9 26. 26.2...
115,[ 24.8 25. 25.2 25.3 25.4 25.6...,[ 25.5 25.6 25.7 25.9 26. 26.1...,[ 25.6 25.9 26. 26.1 26.3 26.5...,[ 25.6 25.7 25.9 26.1 26.2 26.3...,[ 25.3 25.5 25.6 25.7 25.9 26.1...,[ 25.6 25.9 26. 26.1 26.2 26.4...,[ 25.8 25.9 26.1 26.2 26.3 26.5...,[ 25.8 25.9 26. 26.1 26.3 26.4...,[ 25.3 25.6 25.7 25.8 25.9 26.1...,[ 25.6 25.9 26. 26.1 26.2 26.4...,...,[ 26.3 26.5 26.6 26.7 26.9 27. ...,[ 26.1 26.2 26.5 26.6 26.7 26.8...,[ 26.9 27.1 27.3 27.4 27.5 27.7...,[ 26.7 27. 27.1 27.2 27.3 27.5...,[ 26.3 26.5 26.7 26.8 26.9 27.1...,[ 25.9 26.2 26.3 26.5 26.6 26.7...,[ 26.7 27. 27.1 27.2 27.4 27.5...,[ 26.4 26.7 26.8 26.9 27. 27.2...,[ 26.1 26.3 26.5 26.6 26.7 26.9...,[ 24.3 25.4 25.5 25.7 25.9 26. ...
116,[ 24.8 24.9 25.1 25.3 25.4 25.5...,[ 25.3 25.7 25.8 25.9 26. 26.2...,[ 25.8 26.1 26.2 26.3 26.5 26.6...,[ 25.5 25.6 25.8 25.9 26.1 26.2...,[ 25.3 25.5 25.7 25.8 25.9 26.1...,[ 25.6 25.9 26. 26.1 26.3 26.4...,[ 25.8 25.9 26.1 26.3 26.4 26.5...,[ 25.8 25.9 26. 26.2 26.3 26.4...,[ 25.3 25.6 25.7 25.8 26. 26.1...,[ 25.6 25.7 25.9 26. 26.1 26.2...,...,[ 26.3 26.5 26.7 26.8 26.9 27. ...,[ 25.9 26.1 26.1 26.3 26.4 26.5...,[ 26.9 27.1 27.3 27.4 27.5 27.6...,[ 25.5 26.6 26.9 27. 27.1 27.3...,[ 26.3 26.5 26.7 26.8 26.9 27.1...,[ 25.9 26.2 26.3 26.5 26.6 26.8...,[ 26.6 26.8 26.9 27.1 27.2 27.3...,[ 26.4 26.7 26.8 26.9 27.1 27.2...,[ 25.9 26. 26.1 26.3 26.4 26.5...,[ 24.5 24.6 25.4 25.6 25.9 26. ...
117,[ 24.8 25.2 25.3 25.4 25.6 25.7...,[ 25.3 25.4 25.7 25.8 25.9 26. ...,[ 25.8 26.1 26.2 26.3 26.5 26.7...,[ 25.3 25.4 25.6 25.7 25.8 25.9...,[ 25.3 25.5 25.7 25.8 26. 26.1...,[ 25.6 25.9 26. 26.1 26.3 26.4...,[ 25.9 26.1 26.3 26.4 26.5 26.7...,[ 25.6 25.8 25.9 26. 26.1 26.3...,[ 25.3 25.6 25.7 25.8 26. 26.1...,[ 25.6 25.9 26. 26.1 26.2 26.4...,...,[ 26.3 26.5 26.7 26.8 26.9 27. ...,[ 25.9 26.1 26.1 26.3 26.4 26.5...,[ 26.9 27.1 27.3 27.4 27.5 27.7...,[ 26.6 26.8 27. 27.1 27.3 27.4...,[ 26.3 26.5 26.6 26.7 26.9 27.1...,[ 25.8 25.9 26.1 26.2 26.3 26.4...,[ 26.7 27. 27.1 27.2 27.4 27.5...,[ 26.4 26.7 26.8 26.9 27. 27.2...,[ 25.9 26.1 26.3 26.4 26.5 26.7...,[ 25.3 25.6 25.7 25.9 26. 26.1...
118,[ 24.8 24.9 25.2 25.3 25.4 25.6...,[ 25.5 25.7 25.8 25.9 26.1 26.2...,[ 25.9 26.1 26.2 26.3 26.5 26.7...,[ 25.3 25.4 25.5 25.7 25.8 25.9...,[ 25.3 25.5 25.6 25.7 25.9 26.1...,[ 25.6 25.8 26. 26.1 26.2 26.5...,[ 25.9 26.1 26.2 26.3 26.4 26.6...,[ 25.5 25.6 25.8 25.9 26. 26.2...,[ 25.3 25.6 25.7 25.8 26. 26.1...,[ 25.6 25.9 26. 26.1 26.2 26.4...,...,[ 26.3 26.6 26.7 26.8 26.9 27.1...,[ 25.9 26.1 26.3 26.4 26.5 26.7...,[ 26.9 27.2 27.3 27.4 27.5 27.7...,[ 26.6 26.9 27. 27.1 27.3 27.4...,[ 26.3 26.5 26.7 26.8 26.9 27.1...,[ 25.8 26.1 26.2 26.3 26.4 26.6...,[ 26.7 27. 27.1 27.2 27.4 27.5...,[ 26.4 26.7 26.8 26.9 27.1 27.2...,[ 25.9 26.3 26.4 26.5 26.7 26.8...,[ 25.3 25.5 25.6 25.8 25.9 26. ...

In [8]:
# чтение данных
h_X_df = get_hierarhical_X_df(path_to_hierarhical_X_data)
display(h_X_df)

                detector_0  detector_1  detector_2  detector_3  detector_4  \
Row Data point
0   0               25.500      25.300      25.100      25.100      25.500
    1               25.700      25.500      25.300      25.300      25.700
    2               25.800      25.700      25.500      25.400      25.900
    3               25.900      25.800      25.600      25.500      26.000
    4               26.100      25.900      25.900      25.700      26.100
...                    ...         ...         ...         ...         ...
118 59             -39.598     -31.496     -38.781     -42.332     -37.094
    60              35.327      31.496      39.192      39.598      35.327
    61             -34.871     -36.661     -32.985     -35.327     -41.569
    62             -30.984      35.327      33.466      32.496      40.398
    63               0.000       0.000       0.000       0.000       0.000

                detector_5  detector_6  detector_7  detector_8  detector_9  \
Row Data point
0   0               25.500      25.100      25.800      25.800      25.800
    1               25.700      25.300      25.900      25.900      26.000
    2               25.900      25.400      26.000      26.100      26.100
    3               26.000      25.500      26.100      26.200      26.300
    4               26.100      25.600      26.200      26.300      26.400
...                    ...         ...         ...         ...         ...
118 59              41.952     -38.781     -45.255     -43.081      42.332
    60             -35.327      37.094      44.542      41.183      34.871
    61             -39.598     -33.466     -37.094     -38.781     -41.183
    62              38.367      32.985     -36.222      36.661      39.192
    63               0.000       0.000       0.000       0.000       0.000

                ...  detector_390  detector_391  detector_392  detector_393  \
Row Data point  ...
0   0           ...        24.800        25.000        24.800        24.700
    1           ...        25.100        25.300        24.900        24.900
    2           ...        25.200        25.400        25.100        25.000
    3           ...        25.300        25.500        25.200        25.100
    4           ...        25.500        25.700        25.300        25.300
...             ...           ...           ...           ...           ...
118 59          ...        29.394       -37.947        38.367        38.367
    60          ...       -33.941        37.523       -31.496        31.496
    61          ...        30.984       -32.985       -35.777       -37.094
    62          ...       -28.844        32.000        33.466        34.409
    63          ...         0.000         0.000         0.000         0.000

                detector_394  detector_395  detector_396  detector_397  \
Row Data point
0   0                 24.700        20.000        24.700        24.700
    1                 24.900        24.900        24.900        24.900
    2                 25.000        25.100        25.000        25.000
    3                 25.100        25.200        25.100        25.100
    4                 25.300        25.300        25.300        25.300
...                      ...           ...           ...           ...
118 59               -36.222       -36.222       -40.000       -39.598
    60                30.463        35.777        38.367        37.523
    61                28.284        30.463       -35.777       -35.327
    62               -29.933        30.463        33.466        33.941
    63                 0.000         0.000         0.000         0.000

                detector_398  detector_399
Row Data point
0   0                 25.000        25.000
    1                 25.200        25.200
    2                 25.300        25.300
    3                 25.400        25.500
    4                 25.600        25.600
...                      ...           ...
118 59               -30.984       -28.844
    60               -33.466       -33.466
    61                32.000        32.000
    62                30.984       -28.284
    63                 0.000         0.000

[7616 rows x 400 columns]

In [9]:
# чтение данных
Y_df = get_Y_df(path_to_Y_data)
display(Y_df)

,detector_0,detector_1,detector_2,detector_3,detector_4,detector_5,detector_6,detector_7,detector_8,detector_9,...,detector_390,detector_391,detector_392,detector_393,detector_394,detector_395,detector_396,detector_397,detector_398,detector_399
Row,,,,,,,,,,,,,,,,,,,,,
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
111,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
112,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
113,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
114,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0